services:
  instafix:
    image: ghcr.io/gigirassy/instafix:main
    restart: unless-stopped
    expose:
      - "3000"                       # choose loadbalancer of your choice
    networks:
      - backend
    mem_limit: 20m
    environment:
      - SOCKS_PROXIES=socks5h://proxy:1080 # change this! its required for a public instance!
